<?php

define( 'LAN_FILES_H1', 'Files in the sandbox' );
define( 'LAN_ADD_FILE_H1', 'Add file' );
define( 'LAN_FILES_MENU', 'Click to open/add file' );
define( 'LAN_FILES_CLOSE', 'close file' );
define( 'LAN_FILES_SAVE', 'save changes' );
define( 'LAN_RUN', 'run' );
define( 'LAN_CODE_DOWNLOAD', 'download file' );
define( 'LAN_CODE_DELETE_FILE', 'delete file' );
define( 'LAN_CODE_NEW_PANE', 'new pane' );
define( 'LAN_CODE_TOGLE_OUT', 'togle output' );
define( 'LAN_CODE_OPTIONS', 'sandbox options' );
define( 'LAN_CODE_SAVE_ALL', 'save all changes' );
define( 'LAN_CODE_USER', 'user settings' );
define( 'LAN_CODE_ABOUT', 'About' );
define( 'LAN_CODE_SANDBOX_H1', 'Sandbox' );
define( 'LAN_CODE_ERR_FILE_NAME', 'Incorrect file name' );
define( 'LAN_CODE_ERR_FILE_TYPE', 'Incorrect file type' );
define( 'LAN_CODE_ERR_FILE_EXISTS', 'File already exists' );
define( 'LAN_CODE_ERR_EMBED_NAME', 'Name can\'t be empty' );
define( 'LAN_CODE_ERR_EMBED_FILE', 'Select file to run' );
define( 'LAN_CODE_ERR_EMBED_FILES', 'Don\'t forget to include some files' );
define( 'LAN_CODE_ERR_TIMEOUT', 'timeout...' );
define( 'LAN_CODE_RUN_NO_OPTIONS', 'No run options available for this type of file' );
define( 'LAN_CODE_RUN_HTML_DC', 'HTML doctype' );
define( 'LAN_CODE_RUN_URL_QUERY', 'url query' );
define( 'LAN_CODE_RUN_JS_LIBS', 'JS Libraries' );
define( 'LAN_CODE_RUN_CSS_FRMW', 'CSS Frameworks' );
define( 'LAN_CODE_RUN_CUST_CSS', 'custom css' );
define( 'LAN_CODE_RUN_CUST_SCRIPT', 'custom scripts' );
define( 'LAN_CODE_RUN_CUST_CSS_DESC', 'add one url (or filename) per line' );
define( 'LAN_CODE_RUN_POST_DATA', 'POST data' );
define( 'LAN_CODE_RUN_POST_DATA_DESC', 'add post data as key=value pairs<br>(one per line)' );
define( 'LAN_CODE_RUN_GET_DATA', 'GET data' );
define( 'LAN_CODE_RUN_GET_DATA_DESC', 'add get data as key=value pairs<br>(one per line)' );
define( 'LAN_CODE_RUN_PHP_VER', 'PHP version' );
define( 'LAN_CODE_OUTPUT', 'Output' );
define( 'LAN_CODE_RUN_NO_OPTIONS', '' );